### ISSUE TITLE
VS403247: Unable to access the package location

### ISSUE THREAD

**Issue by vishnu4** [MicrosoftDocs/vsts-docs#1047]
getting the following error when i try to run import.  not sure the best way to troubleshoot

[Info   @21:23:28.164] [Info] Microsoft Team Foundation Server (R) Tfs Migrator Tool version 16.131.27716.2
                       [Info] Copyright (C) Microsoft Corporation. All rights reserved.
                       [Info] Executing at 2018-06-14T01:23:28.1562638Z:
                       [Info] tfsmigrator  import /importFile:D:\TfsMigrator\Logs\DefaultCollection\20180613_174159\import.json
[Info   @21:23:28.165] -------------------------------------
                         Validating Import File
                       -------------------------------------
                       Validating import specification file...
[Info   @21:23:28.623] Validation completed with an error.
[Error  @21:23:28.625] + [Error] VS403247: Unable to access the package location 'https://XXXX.blob.core.windows.net/'.
                       Additional Details:
                       delimiter.
[Info   @21:23:28.626] See our documentation for assistance: https://aka.ms/VSTSMigrationTroubleshooting
[Error  @21:23:28.636] Microsoft.VisualStudio.Services.WebApi.PackageLocationNotSupportedException: VS403247: Unable to access the package location 'https://dynamisdryrunstorage.blob.core.windows.net/'.
                       Additional Details:
                       delimiter. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
                          at System.Net.HttpWebRequest.GetResponse()
                          at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
                          --- End of inner exception stack trace ---
                          at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
                          at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.<>c__DisplayClassb.<ListBlobs>b__a(IContinuationToken token)
                          at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext()
                          at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
                          at Microsoft.VisualStudio.Services.DataImport.Extensions.CloudBlobStorageProvider.Initialize(TimeSpan minAllowExpiry)
                          --- End of inner exception stack trace ---
                          at Microsoft.VisualStudio.Services.DataImport.Extensions.CloudBlobStorageProvider.Initialize(TimeSpan minAllowExpiry)
                          at Microsoft.VisualStudio.Services.DataImport.Extensions.DataImportPackageExtensions.CheckIsValid(DataImportPackage package, ITFLogger logger, IVssRequestContext requestContext)
                          at TfsMigrator.DataImportPackageHelper.CheckIsValid()
                          at TfsMigrator.TfsMigratorCommandImport.RunImpl()
[Info   @21:23:28.636] Skipping the import because there were validation errors.
[Info   @21:23:28.637] Execution Time: 0:00:00.504372
[Info   @21:23:28.638] Output Folder:  D:\TfsMigrator\Logs\Imports\20180613_212328

**Comment by steved0x** [comment]
@vishnu4 I'm sorry that you ran into trouble. This GitHub repo is intended for documentation feedback, and the best place for you to post your question is here:

https://developercommunity.visualstudio.com/spaces/21/index.html

However, let me see if I can give a couple of ideas to try before you file a request there. My best guess to start would be to verify everything in [this step](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts#uploading-the-dacpac) and then to verify the connectivity and access to the ` https://dynamisdryrunstorage.blob.core.windows.net/` Azure storage account. That is just a guess as that isn't my specialty.

Thank you,
Steve

**Comment by vishnu4** [comment]
sure thing.  the issue ended up being the fact that in the instructions it was unclear what type of azure storage to use: blob/file/etc.  And after i chose one (blob), i would need to create a container in that blob storage.  and if i used blob storage, i would have to include the container name in the url.  so instead of using 
https://XXX.blob.core.windows.net/
as my location, i needed to use
https://XXX.blob.core.windows.net/blobcontainername/

**Comment by steved0x** [comment]
@vishnu4 I am glad you got it resolved, and I will see if I can get that documentation updated to clarify that -it looks right [here](https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts#import-specification-file) would be a good place to clarify that?

**Comment by vishnu4** [comment]
absolutely!  Thank you.
