### ISSUE TITLE
Validating service identities during TfsMigrator validate

### ISSUE THREAD

**Issue by ravneetDevops** [MicrosoftDocs/vsts-docs#1108]
I am encountering below error while running TfsMigrator validate. Can you please help with the resolution?
[Error  @16:47:05.120] Microsoft.TeamFoundation.Framework.Server.ActionDeniedBySubscriberException: Exception of type 'Microsoft.TeamFoundation.Framework.Server.ActionDeniedBySubscriberException' was thrown.
                          at Microsoft.TeamFoundation.Framework.Server.TeamFoundationEventService.Publish(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Boolean runSynchronously, Exception& exception)
                          at Microsoft.TeamFoundation.Framework.Server.TeamFoundationEventService.PublishDecisionPoint(IVssRequestContext requestContext, Object notificationEvent)
                          at Microsoft.VisualStudio.Services.Identity.PlatformIdentityStore.ReadIdentities(IVssRequestContext requestContext, IdentityDomain hostDomain, IList`1 descriptors, QueryMembership queryMembership, Boolean extendedProperties, IEnumerable`1 propertyNameFilters, Boolean includeRestrictedMembers, Boolean bypassCache, Boolean filterResults)
                          at Microsoft.VisualStudio.Services.Identity.PlatformIdentityService.ReadIdentities(IVssRequestContext requestContext, IList`1 descriptors, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters, Boolean includeRestrictedVisibility)
                          at Microsoft.VisualStudio.Services.Identity.CompositeIdentityService.ReadIdentities(IVssRequestContext requestContext, IList`1 descriptors, QueryMembership queryMembership, IEnumerable`1 propertyNameFilters, Boolean includeRestrictedVisibility)
                          at Microsoft.VisualStudio.Services.Identity.DataImport.IdentitySnapshotValidator.TryVerifyIdentities(DataImportValidationContext validationContext, Boolean includeInactiveUsers, IList`1& windowsUsers, IList`1& windowsGroups)
                          at Microsoft.VisualStudio.Services.Identity.Import.IdentityImportValidation.Run(DataImportValidationContext validationContext, String& message)
                          at Microsoft.TeamFoundation.Framework.Server.DataImport.DataImportValidator.Run(DataImportValidationType filter)
[Info   @16:47:05.123] Validation completed 'Validate Identities' with result Failed, message Validate Identities Failed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64a8f6c-dcd1-5ad6-e0e8-f3c79ab55ada
* Version Independent ID: a53a4938-e09a-505b-ec42-9ee61405cd09
* Content: [Resolve validation errors - VSTS](https://docs.microsoft.com/en-us/vsts/work/customize/import-process/resolve-errors?toc=%2Fvsts%2Fwork%2Fcustomize%2Ftoc.json&bc=%2Fvsts%2Fwork%2Fcustomize%2Fbreadcrumb%2Ftoc.json&view=vsts#feedback)
* Content Source: [docs/work/customize/import-process/resolve-errors.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/customize/import-process/resolve-errors.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
Note, possibly related to https://github.com/MicrosoftDocs/vsts-docs/issues/1107

**Comment by sadjadbp** [comment]
You should take look at TfsMigrator logs as mentioned here

https://docs.microsoft.com/en-us/vsts/articles/migration-import?view=vsts

are you at validation phase or migration, probably contacting VSTS CSS/support would be best case so we can get all the data we need.

**Comment by KathrynEE** [comment]
@ravneetDevops - Thank you for your inquiry. Please take a look at the TfsMigrator logs as mentioned in the above comment. I'm closing this issue as CSS/support would be better able to help.
