### ISSUE TITLE
Error trying to publish universal package.

### ISSUE THREAD

**Issue by garthbf** [MicrosoftDocs/vsts-docs#2508]
I ran the command to publish and it tried to install the tooling.
this is the error:

An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied: 'C:\\Users\\xxxxx\\.
vsts\\cli\\tools\\artifacttool\\d95d5457-e963-4b3a-8bd8-737ca04c8a66' -> 'C:\\Users\\xxxxx\\.vsts\\cli\\tools\\artifac
ttool\\ArtifactTool_win10-x64_0.2.74'
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 203, in _command_handl
er
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\universal.py", line 41,
 in publish_package
    return artifact_tool.publish_universal(team_instance, feed, name, version, description, path)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line
30, in publish_universal
    return self.run_artifacttool(team_instance, args, "Publishing")
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line
44, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, self._process_stderr)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line
 68, in run
    self.start(command_args, env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line
 38, in start
    env=env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by garthbf** [comment]
I ran the command with the --debug. 
the error is:
VS30063: You are not authorized to access https://vsblobprodscussu5.vsblob.visualstudio.com.

**Comment by garthbf** [comment]
https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=vsts&tabs=azuredevops

Garth Frazer
Premera Blue Cross
garth.frazer@premera.com<mailto:garth.frazer@premera.com>
Work    - 425.918.3186
Cell    - 360.421.3326

**Comment by steved0x** [comment]
@garthbf Thanks for letting me know the URL, I am assigning this issue.

**Comment by elbatk** [comment]
Hi @garthbf , this seems to just be an auth issue with your server. Since this issue, we have changed to using the Azure CLI with the Azure DevOps extension. Here is a bit about authing with your service using `az devops login`: https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/devops?view=azure-cli-latest#ext-azure-devops-az-devops-login. Are you able to run other commands in your org via the CLI?

**Comment by garthbf** [comment]
Sorry I should have replied awhile ago. 
this issue is on our side with some kind of firewall rule or bluecoat. I was ableto get the CLI to work on out of our build servers that is in a different location.

**Comment by elbatk** [comment]
Awesome, that's good to hear! @garthbf . Going to close this issue now then, glad you've got it sorted.
