### ISSUE TITLE
"Powershell on target machines" always fails with winrm could not process the request.

### ISSUE THREAD

**Issue by yashwanthkota2006** [MicrosoftDocs/vsts-docs#2532]
We have done with the configuration of the agent to do credSSP authentication. I would like to know what are all the configurations and settings that need to be done in case of task to succeed with credSSP authentication.

**Comment by yashwanthkota2006** [comment]
Updating the thread with the following exception:
2018-11-19T14:38:21.1451467Z Permission denied while trying to connect to the target machine xxx on the port:5985 via power shell remoting. Please check the following link for instructions: https://go.microsoft.com/fwlink/?LinkID=390236System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server xxx failed with the following error message : WinRM cannot process the request. The following error with errorcode 0x80090311 occurred while using Kerberos authentication: We can't sign you in with this credential because your domain isn't available. Make sure your device is connected to your organization's network and try again. If you previously signed in on this device with another credential, you can sign in with that credential.  
2018-11-19T14:38:21.1452700Z  Possible causes are:
2018-11-19T14:38:21.1452966Z   -The user name or password specified are invalid.
2018-11-19T14:38:21.1453388Z   -Kerberos is used when no authentication method and no user name are specified.
2018-11-19T14:38:21.1453720Z   -Kerberos accepts domain user names, but not local user names.
2018-11-19T14:38:21.1454087Z   -The Service Principal Name (SPN) for the remote computer name and port does not exist.
2018-11-19T14:38:21.1454480Z   -The client and remote computers are in different domains and there is no trust between the two domains.
2018-11-19T14:38:21.1454843Z  After checking for the above issues, try the following:
2018-11-19T14:38:21.1455143Z   -Check the Event Viewer for events related to authentication.
2018-11-19T14:38:21.1455552Z   -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
2018-11-19T14:38:21.1455969Z  Note that computers in the TrustedHosts list might not be authenticated.
2018-11-19T14:38:21.1456401Z    -For more information about WinRM configuration, run the following command: winrm help config. For more information, see the about_Remote_Troubleshooting Help topic.
2018-11-19T14:38:21.1456834Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2018-11-19T14:38:21.1457501Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2018-11-19T14:38:21.1457878Z    at System.Management.Automation.RemoteRunspace.Open()
2018-11-19T14:38:21.1458232Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2018-11-19T14:38:21.1458663Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2018-11-19T14:38:21.1459062Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2018-11-19T14:38:21.1459404Z    at System.Threading.Tasks.Task.Execute()
2018-11-19T14:38:21.1459708Z --- End of stack trace from previous location where exception was thrown ---
2018-11-19T14:38:21.1460051Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-19T14:38:21.1460425Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-19T14:38:21.1460845Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2018-11-19T14:38:21.1462215Z --- End of stack trace from previous location where exception was thrown ---
2018-11-19T14:38:21.1462541Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-19T14:38:21.1463041Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-19T14:38:21.1463650Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2018-11-19T14:38:21.1464249Z --- End of stack trace from previous location where exception was thrown ---
2018-11-19T14:38:21.1464682Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-19T14:38:21.1465054Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-19T14:38:21.1465478Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2018-11-19T14:38:21.1465885Z --- End of stack trace from previous location where exception was thrown ---
2018-11-19T14:38:21.1466224Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-11-19T14:38:21.1466579Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-11-19T14:38:21.1466997Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2018-11-19T14:38:21.1467228Z

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.
