### ISSUE TITLE
Unable to follow instructions

### ISSUE THREAD

**Issue by fcanas** [MicrosoftDocs/vsts-docs#2548]
In the portion: Install the provisioning profile during your build
1. Add the Install Apple Provisioning Profile task to your build before the Xcode or Xamarin.iOS task.

I can't figure out why it's not working. 

Error: /usr/bin/security failed with return code: 1

I must be doing something wrong, but I've only followed these instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e66a70d-e359-9d0a-0143-a9e43b263795
* Version Independent ID: 7b320a02-0a63-947a-3017-4826ab461112
* Content: [Sign Your Mobile App During CI - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=vsts&tabs=apple-install-during-build)
* Content Source: [docs/pipelines/apps/mobile/app-signing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/mobile/app-signing.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by albernazf** [comment]
I keep getting this error, I saw in varies places that to fix it it needs to change the last line of apksigner from 
call "%java_exe%" %javaOpts% -Djava.ext.dirs="%frameworkdir%" -jar "%jarpath%" %params%
to 
call "%java_exe%" %javaOpts% -classpath "%frameworkdir%" -jar "%jarpath%" %params%
which then worked for me locally, but obviously I can't change that on the hosted Azure Devops


Failed to load signer "signer #1"
2018-12-16T01:44:02.0016268Z java.io.IOException: Invalid keystore format
2018-12-16T01:44:02.0019884Z 	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
2018-12-16T01:44:02.0020362Z 	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
2018-12-16T01:44:02.0020642Z 	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
2018-12-16T01:44:02.0023554Z 	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
2018-12-16T01:44:02.0023866Z 	at java.security.KeyStore.load(KeyStore.java:1445)
2018-12-16T01:44:02.0026529Z 	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:604)
2018-12-16T01:44:02.0029159Z 	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:546)
2018-12-16T01:44:02.0029428Z 	at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:500)
2018-12-16T01:44:02.0029628Z 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:236)
2018-12-16T01:44:02.0029782Z 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:93)

**Comment by ShahSwapnil** [comment]
I am having the exact same problem as fcanas.

**Comment by davidstaheli** [comment]
Thanks for reporting this. I think it has been fixed, but we're going to move this issue to a different repo for better tracking:
https://github.com/Microsoft/azure-pipelines-tasks

/move to Microsoft/azure-pipelines-tasks
