### ISSUE TITLE
Azure Pipelines - Job Custom Condition - Syntax for parameters in Job Status Functions

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/vsts-docs#2623]
I'm trying to configure a Pipeline Job to run under a custom condition, and I'm having a hard time writing the correct syntax for the custom condition.

I have 3 jobs in total:
- 1st Job Name: Deployment
- 2nd Job Name: Validation
- 3rd Job Name: Rollback

I want the Rollback job to run only if Deployment was successful and Validation failed. Therefore, I wrote the variable expression like so:
![image](https://user-images.githubusercontent.com/7240365/49316938-3713bb80-f4b8-11e8-85d0-6cc418f809c5.png)

This syntax obviously isn't correct. Below is the error it provides. Please advise on what the expression should look like.

Thank you!

##[Error 1]
Exception Message: Unexpected symbol: ')'. Located at position 27 within expression: and(succeeded('Deployment'), failed('Validation')). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996 (type ParseException)
Exception Stack Trace:    at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.HandleEndParameter(ParseContext context) in C:\t\a\_work\6\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 254
   at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.CreateTree(ParseContext context) in C:\t\a\_work\6\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 44
   at Microsoft.TeamFoundation.DistributedTask.Expressions.ExpressionParser.CreateTree(String expression, ITraceWriter trace, IEnumerable`1 namedValues, IEnumerable`1 functions) in C:\t\a\_work\6\s\DistributedTask\Client\WebApi\Expressions\ExpressionParser.cs:line 18
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.PhaseConditionEvaluator.ShouldExecutePhase(IVssRequestContext requestContext, ReleaseEnvironment releaseEnvironment, DeployPhaseSnapshot deployPhaseSnapshot, AutomationEngineInput automationEngineInput) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\PhaseConditionEvaluator.cs:line 26
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 265
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.RunDeployPhase(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 465
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.MoveWorkflowForward(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, ReleaseDeployPhase deployPhase, Func`5 runDeployPhase, Action`4 acceptStep, Action`3 rejectStep) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 297
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.<>c__DisplayClass10_0.<HandleDeployPhaseCompletion>b__0(Release r, ReleaseEnvironment e, ReleaseEnvironmentStep s, ReleaseDeployPhase p) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 162
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseOrchestrator.UpdateDeployPhaseAndMoveWorkflowForward(Int32 releaseId, Int32 deployStepId, Int32 releaseDeployPhaseId, DeployPhaseStatus deployPhaseStatus, DeploymentOperationStatus operationStatus, Action`4 moveWorkflowForward, Action`4 handleException, Boolean shouldUpdateIfAnyStatus) in C:\t\a\_work\6\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseOrchestrator.cs:line 401

**Comment by steved0x** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml

**Comment by vtbassmatt** [comment]
Specifically, see [the Dependencies section](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=vsts&tabs=yaml#dependencies).

Something like: `and(eq(dependencies.Deployment.result, 'Succeeded'), eq(dependencies.Validation.result, 'Failed'))`

**Comment by blaze515** [comment]
Hi. How can you do this in the newer version of Azure Devops? I get an error saying that dependencies is not recognized.
