### ISSUE TITLE
Jenkins Queue Job fails with URISyntaxException: Illegal character in scheme name at index 3

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/vsts-docs#3123]
In the last step, we trigger a Jenkins build from Azure DevOps. While the exact same build works fine over and over again when it is getting triggered from inside the Jenkins itself, I get an error every time it happens from Azure DevOps with the following message:

```
2019-01-24T16:37:07.5464485Z FATAL: Illegal character in scheme name at index 3: git@ssh.dev.azure.com:v3/XamarinDevOps/Java-Demo/MyShuttleCalc
2019-01-24T16:37:07.5465310Z java.net.URISyntaxException: Illegal character in scheme name at index 3: git@ssh.dev.azure.com:v3/XamarinDevOps/Java-Demo/MyShuttleCalc
2019-01-24T16:37:07.5465676Z 	at java.net.URI$Parser.fail(URI.java:2848)
2019-01-24T16:37:07.5465793Z 	at java.net.URI$Parser.checkChars(URI.java:3021)
2019-01-24T16:37:07.5465856Z 	at java.net.URI$Parser.parse(URI.java:3048)
2019-01-24T16:37:07.5465915Z 	at java.net.URI.&lt;init&gt;(URI.java:588)
2019-01-24T16:37:07.5466157Z 	at java.net.URI.create(URI.java:850)
2019-01-24T16:37:07.5466804Z Caused: java.lang.IllegalArgumentException: Illegal character in scheme name at index 3: git@ssh.dev.azure.com:v3/XamarinDevOps/Java-Demo/MyShuttleCalc
2019-01-24T16:37:07.5467941Z 	at java.net.URI.create(URI.java:852)
2019-01-24T16:37:07.5468122Z 	at hudson.plugins.tfs.CommitParameterAction.canOriginateFrom(CommitParameterAction.java:44)
2019-01-24T16:37:07.5468247Z 	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1069)
2019-01-24T16:37:07.5468613Z 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1187)
2019-01-24T16:37:07.5468761Z 	at hudson.scm.SCM.checkout(SCM.java:504)
2019-01-24T16:37:07.5468828Z 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
2019-01-24T16:37:07.5469119Z 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
2019-01-24T16:37:07.5469326Z 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
2019-01-24T16:37:07.5469465Z 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
2019-01-24T16:37:07.5469548Z 	at hudson.model.Run.execute(Run.java:1810)
2019-01-24T16:37:07.5469778Z 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
2019-01-24T16:37:07.5469900Z 	at hudson.model.ResourceController.execute(ResourceController.java:97)
2019-01-24T16:37:07.5469971Z 	at hudson.model.Executor.run(Executor.java:429)
2019-01-24T16:37:07.5470194Z Archiving artifacts
2019-01-24T16:37:07.5470337Z Recording results... JUnit (1 file) JaCoCo (30 files). Compressing... Done.
2019-01-24T16:37:07.5470457Z Finished: FAILURE
```

Looks like a problem with the Git repo URL, mh?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a995c1-0297-29df-ef46-408edccd2958
* Version Independent ID: f719cab3-cbe1-f2cd-74c2-ec52ba4549e2
* Content: [Build a package for Maven with Jenkins and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/java/labs/mavenpmjenkins/?view=vsts#integrate-azure-devops-services-team-build-and-jenkins)
* Content Source: [docs/java/labs/mavenpmjenkins/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/java/labs/mavenpmjenkins/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by kurisa12** [comment]
Try to remove git@ from your repo URL. It worked for me.

**Comment by robinmanuelthiel** [comment]
That did the trick for me as well, thank you, @kurisa12! I have created a new screenshot, if anyone wants to replace it. We should also mention in the docs that one should only copy the part AFTER `git@` from the repo URL...

<img width="787" alt="screen shot 2019-01-28 at 17 14 22" src="https://user-images.githubusercontent.com/5874465/51849918-f5b95400-2320-11e9-8db8-46693b1eb95d.png">

**Comment by davidstaheli** [comment]
The docs have been updated with this information.  It should be live within a few days.  Thanks very much for reporting it, and for the screen shot!
