### ISSUE TITLE
Issues with Devops Slack integration - Exception with the Slack Update Message Hook

### ISSUE THREAD

**Issue by Yu-457** [MicrosoftDocs/vsts-docs#3421]
Hi Team, 
we got an issue with the Slack integration of Devops. 
Service Hooks for Builds, deleted Items etc. are working fine, but when we add a hook of the type "work item created" we get an exception.
Could this be a bug? Other types are working fine - Attached the details.

![image](https://user-images.githubusercontent.com/47786587/53025589-702d4d80-3461-11e9-8d3d-c2480b3eb8db.png)
![image](https://user-images.githubusercontent.com/47786587/53025617-81765a00-3461-11e9-8433-857d26a4557e.png)
-> 
ystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Can not convert Object to String.
 at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
 at Microsoft.VisualStudio.Services.ServiceHooks.Consumers.Slack.PostMessageToChannelAction.<>c.<BuildAttachmentForWorkItemUpdated>b__73_1(List`1 currFields, JProperty field) in d:\v2.0\P1\_work\10\s\ServiceHooks\Sdk\Consumers\Slack\PostMessageToChannelAction.cs:line 587
 at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
 at Microsoft.VisualStudio.Services.ServiceHooks.Consumers.Slack.PostMessageToChannelAction.BuildAttachmentForWorkItemUpdated(JObject resource) in d:\v2.0\P1\_work\10\s\ServiceHooks\Sdk\Consumers\Slack\PostMessageToChannelAction.cs:line 582
 at Microsoft.VisualStudio.Services.ServiceHooks.Consumers.Slack.PostMessageToChannelAction.TransformEvent(Event raisedEvent, HandleEventArgs e) in d:\v2.0\P1\_work\10\s\ServiceHooks\Sdk\Consumers\Slack\PostMessageToChannelAction.cs:line 288
 at Microsoft.VisualStudio.Services.ServiceHooks.Consumers.Slack.PostMessageToChannelAction.HandleEvent(IVssRequestContext requestContext, Event raisedEvent, HandleEventArgs e) in d:\v2.0\P1\_work\10\s\ServiceHooks\Sdk\Consumers\Slack\PostMessageToChannelAction.cs:line 249
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at Microsoft.VisualStudio.Services.ServiceHooks.Consumers.ServiceHooksConsumerService.GetConsumerActionTaskForNotification(IVssRequestContext requestContext, Notification notification) in d:\v2.0\P1\_work\10\s\ServiceHooks\Sdk\Consumers\ServiceHooksConsumerService.cs:line 320
 at Microsoft.VisualStudio.Services.ServiceHooks.Server.ServiceHooksService.<NotifyConsumerAsync>d__68.MoveNext() in d:\v2.0\P1\_work\10\s\ServiceHooks\Service\Server\ServiceHooksService.cs:line 2785

**Comment by steved0x** [comment]
@Yu-457 Sorry that you ran into trouble, thanks for letting us know. I will let the product team know, and I am closing this issue here, since the issues in this repo are for documentation feedback. Although I am forwarding this to the product team, I recommend that you file directly with them by creating an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

You can also submit other product feedback, (including bug reports like this), or feature requests, by choosing **Product feedback** at the bottom of any article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

Thank you.
