### ISSUE TITLE
Error message 'Source path does not exist' when Source is a unc path on a remote machine 

### ISSUE THREAD

**Issue by GITGW** [MicrosoftDocs/vsts-docs#471]

**Comment by GITGW** [comment]
Preparing task execution handler.
Executing the powershell script: D:\a_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\1.0.42\WindowsMachineFileCopy.ps1

System.Management.Automation.RuntimeException: Source path '\192.168.100.253\d$\REPO' does not exist. ---> System.Management.Automation.RuntimeException: Source path '\192.168.100.253\d$\REPO' does not exist.
--- End of inner exception stack trace ---
at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection1 input, PSDataCollection1 output, PSInvocationSettings settings)
at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection1 input, PSDataCollection1 output, PSInvocationSettings settings)
at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)

LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by steved0x** [comment]
@GITGW Can you let me know which article you were reading when you encountered this issue?
