### ISSUE TITLE
AndroidSigning@3 fails to sign - java.io.IOException: Keystore was tampered with, or password was incorrect

### ISSUE THREAD

**Issue by MouthOfMadness** [MicrosoftDocs/vsts-docs#6097]
Is AndroidSigning@3 using a different keystore format and if so, how do you generate it?

I'm receiving a DevOps YAML task signing error using AndroidSigning@3
VS2019 16.3.5 generated the keystore, using Ad-Hoc
The keystore is uploaded as a secure file.
The passwords are set as secure

Using the same pipeline, but different android signing tasks:
**This works:**

- task: AndroidSigning@2
    displayName: "align and sign"  
    inputs:
      apkFiles: '$(outputDirectory)/*.apk'    
      jarsign: true    
      jarsignerKeystoreFile: 'myapp-keystore.keystore'
      jarsignerKeystorePassword: '$(keystorePassword)'
      jarsignerKeystoreAlias: 'myapp-keystore'
      jarsignerKeyPassword: '$(keyPassword)'      
      zipalign: true

**This fails** (see error details below)

- task: AndroidSigning@3
    displayName: 'align and sign'
    inputs:
      apkFiles: '$(outputDirectory)/*.apk'
      apksignerKeystoreFile: 'myapp-keystore.keystore'
      apksignerKeystorePassword: '$(keystorePassword)'
      apksignerKeystoreAlias: 'myapp-keystore'
      apksignerKeyPassword: '$(keyPassword)'
      zipalign: true

C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Android\android-sdk\build-tools\24.0.3\apksigner.bat" sign --ks d:\a\_temp\myapp-keystore.keystore --ks-pass "pass:***" --ks-key-alias myapp-keystore --key-pass "pass:***" --verbose 

d:\a\1\b\Release\android\com.aiworldwide.myapp.apk"

Failed to load signer "signer #1"

java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:785)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:604)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:546)	at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:500)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:236)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:93)

Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:783)
	... 9 more

##[error]Error: The process 'C:\Program Files (x86)\Android\android-sdk\build-tools\24.0.3\apksigner.bat' failed with exit code 2

**Comment by msebolt** [comment]
@MouthOfMadness Thank you for the feedback and for providing your examples.

Since this is a bug it needs to be directed to the product team for review, please use either the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) or the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo and link back to this issue.

**Comment by msebolt** [comment]
Thank you for moving the issue, closing this now.

Please refer to the link above for any additional comment or concerns.
